package termux

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"text/template"
	"time"
)

// ConfOptions are the parts of the generated tmux configuration the dashboard
// can change. Everything else about the file is fixed, because everything else
// about it is load bearing.
type ConfOptions struct {
	// DefaultTerminal is tmux-256color where that terminfo entry exists, and
	// screen-256color where it does not.
	DefaultTerminal string
	HistoryLimit    int
	Mouse           bool
	ExtendedKeys    bool
}

// Normalize fills in the values a caller left out.
func (o ConfOptions) Normalize() ConfOptions {
	if o.DefaultTerminal == "" {
		o.DefaultTerminal = DefaultTerminal()
	}
	if o.HistoryLimit < 100 {
		o.HistoryLimit = 20000
	}
	return o
}

func onOff(v bool) string {
	if v {
		return "on"
	}
	return "off"
}

// The scopes in this template are the point of it. Setting a server option
// with -g or a window option with -s is the usual reason a tmux configuration
// silently does nothing, and several of these are not where their names
// suggest.
//
// window-size is deliberately absent, and must stay absent: a global
// `window-size manual` segfaults the tmux server on the *next* new-session, in
// a configuration file or set live, taking every running session with it. The
// policy is a per window option applied after a session is created; see
// Manager.applySizePolicy.
var confTemplate = template.Must(template.New("tmux.conf").Parse(
	`# Generated by Socrates. Do not edit; it is rewritten on every start.
set -g  status off
set -sg escape-time 0
set -g  default-terminal "{{.DefaultTerminal}}"
set -g  history-limit {{.HistoryLimit}}
set -g  mouse {{.Mouse}}
setw -g aggressive-resize on
set -g  remain-on-exit on
set -g  destroy-unattached off
set -g  exit-empty off
set -g  allow-passthrough on
set -g  set-titles off
set -g  focus-events on
set -s  extended-keys {{.ExtendedKeys}}
set -as terminal-features 'xterm*:extkeys'
set -g  remain-on-exit-format ''
set -g  window-style        'fg=#17181b,bg=#ffffff'
set -g  window-active-style 'fg=#17181b,bg=#ffffff'
`))

// Conf renders the configuration file.
func Conf(o ConfOptions) []byte {
	o = o.Normalize()
	var buf bytes.Buffer
	_ = confTemplate.Execute(&buf, struct {
		DefaultTerminal string
		HistoryLimit    int
		Mouse           string
		ExtendedKeys    string
	}{o.DefaultTerminal, o.HistoryLimit, onOff(o.Mouse), onOff(o.ExtendedKeys)})
	return buf.Bytes()
}

// MinimalConf is what is written when the generated configuration turns out to
// be one tmux will not load. It keeps only what the product cannot do without:
// no status line, a terminal type, a pane that stays after its program exits,
// and the window style that makes the three CLIs choose a light palette.
func MinimalConf(o ConfOptions) []byte {
	o = o.Normalize()
	return []byte(fmt.Sprintf(`# Generated by Socrates as a fallback: the full configuration was refused.
set -g  status off
set -g  default-terminal "%s"
set -g  remain-on-exit on
set -g  window-style        'fg=#17181b,bg=#ffffff'
set -g  window-active-style 'fg=#17181b,bg=#ffffff'
`, o.DefaultTerminal))
}

// WriteConf writes the configuration file, replacing whatever was there.
func WriteConf(path string, o ConfOptions) error {
	return writeConf(path, Conf(o))
}

func writeConf(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}

var (
	terminalOnce sync.Once
	terminalName string
)

// DefaultTerminal is the TERM tmux presents to the programs it runs. A slim
// image without ncurses-term has no tmux-256color entry, and claiming one that
// is not there breaks every curses program in the pane.
func DefaultTerminal() string {
	terminalOnce.Do(func() {
		terminalName = "screen-256color"
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := exec.CommandContext(ctx, "infocmp", "tmux-256color").Run(); err == nil {
			terminalName = "tmux-256color"
		}
	})
	return terminalName
}
